# Generated by Django 5.2.4 on 2026-04-13 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("aspect_w", models.PositiveSmallIntegerField(default=2)),
                ("aspect_h", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                (
                    "size",
                    models.CharField(
                        choices=[("1x1", "1×1"), ("1x2", "1×2"), ("1x3", "1×3")],
                        default="1x1",
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_occupied", models.BooleanField(default=False)),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="service.hall",
                    ),
                ),
            ],
        ),
    ]
