# Generated by Django 5.2.4 on 2026-04-15 21:22

import django.db.models.deletion
from django.db import migrations, models

import tools.models.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="last name"),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="per hour",
                        max_digits=7,
                        verbose_name="salary",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("waiter", "Waiter"),
                            ("chef", "Chef"),
                            ("assistant", "Assistant"),
                            ("barista", "Barista"),
                        ],
                        default="waiter",
                        max_length=20,
                        verbose_name="position",
                    ),
                ),
                (
                    "pin",
                    models.CharField(
                        blank=True,
                        max_length=4,
                        null=True,
                        validators=[tools.models.validators.validate_digits],
                        verbose_name="pin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("finish_time", models.DateTimeField(blank=True, null=True)),
                (
                    "salary_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "is_settled",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the order has been settled (payment finalized).",
                    ),
                ),
                (
                    "settled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of when the worker time was settled. Null if not yet settled.",
                        null=True,
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="worker.worker",
                    ),
                ),
            ],
        ),
    ]
