# Generated by Django 5.2.4 on 2026-04-15 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Addition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "bill_name",
                    models.CharField(
                        blank=True,
                        help_text="Name as it will appear on the bill",
                        max_length=40,
                        null=True,
                        verbose_name="bill name",
                    ),
                ),
                (
                    "vat",
                    models.SmallIntegerField(
                        choices=[
                            (0, "23% VAT"),
                            (1, "8% VAT"),
                            (2, "2% VAT"),
                            (3, "0% VAT"),
                        ],
                        default=0,
                        verbose_name="VAT",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="price"
                    ),
                ),
                (
                    "id_checkout",
                    models.PositiveIntegerField(
                        help_text="Cash register product ID", verbose_name="checkout ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="deleted"),
                ),
                (
                    "priority",
                    models.SmallIntegerField(default=1, verbose_name="priority"),
                ),
            ],
            options={
                "verbose_name": "addition",
                "verbose_name_plural": "additions",
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preparation_location",
                    models.CharField(
                        blank=True,
                        choices=[("bar", "Bar"), ("kitchen", "Kitchen")],
                        default="kitchen",
                        max_length=30,
                        null=True,
                        verbose_name="preparation location",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Item name", max_length=100, verbose_name="name"
                    ),
                ),
                (
                    "bill_name",
                    models.CharField(
                        blank=True,
                        help_text="Name as it will appear on the bill",
                        max_length=40,
                        null=True,
                        verbose_name="bill name",
                    ),
                ),
                (
                    "vat",
                    models.SmallIntegerField(
                        choices=[
                            (0, "23% VAT"),
                            (1, "8% VAT"),
                            (2, "2% VAT"),
                            (3, "0% VAT"),
                        ],
                        default=0,
                        verbose_name="VAT",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Item description",
                        max_length=500,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "daily_stock",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of portions available today. None = unlimited, 0 = sold out.",
                        null=True,
                        verbose_name="daily stock",
                    ),
                ),
                (
                    "id_checkout",
                    models.PositiveIntegerField(
                        help_text="Cash register product ID", verbose_name="checkout ID"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="price"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="deleted"),
                ),
                (
                    "additions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="item_related",
                        to="menu.addition",
                        verbose_name="additions",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "items",
            },
        ),
        migrations.CreateModel(
            name="MenuPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_enabled", models.BooleanField(default=True)),
                ("items", models.ManyToManyField(blank=True, to="menu.item")),
            ],
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "subcategory",
                "verbose_name_plural": "subcategories",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="sub_menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="menu.subcategory",
                verbose_name="subcategory",
            ),
        ),
    ]
