# Generated by Django 5.2.4 on 2026-04-15 21:22

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("menu", "0001_initial"),
        ("service", "0001_initial"),
        ("worker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("closed_and_occupied", "Closed and occupied"),
                        ],
                        default="open",
                        max_length=19,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "discount",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("cash", "Cash"),
                            ("cash_and_card", "Cash and card"),
                        ],
                        default=None,
                        max_length=13,
                        null=True,
                    ),
                ),
                (
                    "guest_count",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Number of people in one the bill (plates per person)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_printed", models.BooleanField(default=False)),
                ("printed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "table",
                    models.ManyToManyField(
                        help_text="Table to which the bill is assigned. Null means take-away",
                        to="service.table",
                    ),
                ),
                (
                    "waiter",
                    models.ForeignKey(
                        help_text="Person who served the customer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="worker.worker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ok", models.BooleanField()),
                (
                    "hn",
                    models.CharField(
                        help_text="Unique fiscal receipt number", max_length=20
                    ),
                ),
                (
                    "bn",
                    models.CharField(help_text="Session receipt number", max_length=20),
                ),
                ("took", models.PositiveIntegerField(help_text="Print time in ms")),
                ("raw_response", models.JSONField(help_text="Full POSNET response")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="order.bill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordering", "Ordering"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("paid", "Paid"),
                            ("canceled", "Canceled"),
                        ],
                        default="ordering",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("bar", "Bar"), ("kitchen", "Kitchen")],
                        default="kitchen",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("readied_at", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="order.bill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_snapshot",
                    models.CharField(
                        help_text="Name of dish or additions", max_length=150
                    ),
                ),
                (
                    "price_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of dish or additions when it was ordered",
                        max_digits=5,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "line_subtotal",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("price_snapshot"), "*", models.F("quantity")
                        ),
                        help_text="Subtotal for this item before discount and additions (price × quantity)",
                        output_field=models.DecimalField(
                            decimal_places=2, max_digits=12
                        ),
                    ),
                ),
                (
                    "line_final_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final price after bill discount. Set when  bill is closed.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("canceled", "Canceled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menu.item"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("item_info", "Item Info"),
                            ("order_info", "Order Info"),
                            ("call", "Call"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("waiting_to_read", "Waiting to Read"),
                            ("read", "Read"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=400, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="worker.worker"
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.order",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.orderitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItemAddition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_snapshot",
                    models.CharField(
                        help_text="Name of dish or additions", max_length=150
                    ),
                ),
                (
                    "price_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of dish or additions when it was ordered",
                        max_digits=5,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "line_subtotal",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("price_snapshot"), "*", models.F("quantity")
                        ),
                        help_text="Subtotal for this item before discount and additions (price × quantity)",
                        output_field=models.DecimalField(
                            decimal_places=2, max_digits=12
                        ),
                    ),
                ),
                (
                    "line_final_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final price after bill discount. Set when  bill is closed.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "addition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menu.addition"
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item_additions",
                        to="order.orderitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
